# Generated by Django 5.0.3 on 2024-03-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimage',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='num_adults',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_children',
            field=models.IntegerField(default=0),
        ),
    ]
