# Generated by Django 5.0.3 on 2024-03-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_remove_hotelimage_price_booking_num_adults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='days',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
