# Generated by Django 5.0.3 on 2024-03-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_detailed_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detailed_desc',
        ),
    ]
