# Generated by Django 5.0.3 on 2024-03-26 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_payment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='Payment',
        ),
    ]
