# Generated by Django 5.0.3 on 2024-03-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_alter_payment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
