# Generated by Django 5.0.3 on 2024-03-26 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_alter_payment_razorpay_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
